---
- name: Create pods using deployment
  hosts: kube
  become: true
  user: root

  tasks:
  - name: create a deployment
    command: kubectl apply -f https://raw.githubusercontent.com/Sonal0409/DevOps_ClassNotes/master/CICD%20pipeline/kubedeployment.yml
